networks:
  march1_network:
    external: true

volumes:
  redis_data:

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:3003"
    environment:
      - NODE_ENV=production
    container_name: march1-gateway
    restart: unless-stopped
    env_file: ".env"
    networks:
      - march1_network
  redis:
    image: redis:latest
    container_name: march-1-ratelimiter-cache
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
